#!/usr/bin/env bash
# hooks/pre_build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Pre_build hook starting..."
if [ "$COMMIT_MSG" != "" ]; then
	GIT_LOG="$(git show -s $SOURCE_COMMIT | grep -i -E 'mariadb1011|mariadb10\.11|mariadb 10\.11|mariadb all|db all|update all images')"

	if [ -z "$GIT_LOG" ]; then
		echo "[***] Aborted: Nothing to do for MariaDB 10.11!"
		exit 1
	fi
fi

echo "[***] Found keyword for MariaDB 10.11: Continue with build..."
