version: '3'
# Define common behavior
x-php56:
  &default-php56
  build:
    context: .
    dockerfile: ./php/php56-fpm/Dockerfile
    args:
      MY_TZ: ${BUILD_TZ}
      VERSION: ${PHP56_VERSION}
  image: degobbis/php56-fpm-alpine:latest

services:
  php56-latest:
    *default-php56
  php56-version:
    << : *default-php56
    image: degobbis/php56-fpm-alpine:${PHP56_VERSION}
