#!/usr/bin/env bash
# hooks/pre_build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Pre_build hook starting..."
if [ "$COMMIT_MSG" != "" ]; then
	GIT_LOG="$(git show -s $SOURCE_COMMIT | grep -i -E 'php81|php8\.1|php 8\.1|php all|update all images')"

	if [ -z "$GIT_LOG" ]; then
		echo "[***] Aborted: Nothing to do for PHP8.1!"
		exit 1
	fi
fi

echo "[***] Found keyword for PHP8.1: Continue with build..."
