#!/usr/bin/env sh

if [ -z "$mysql_options" ]; then
    mysql_options='--protocol=socket -uroot'
fi

if ! type 'execute' &>/dev/null; then
    # Execute mysql statement
    # statement can be passed directly or by HEREDOC
    execute() {
        statement="$1"

        if [ -n "$statement" ]; then
            if ! mysql -ss $mysql_options -e "$statement" &> /dev/null; then
                for i in `seq 30 -1 0`; do
                    if mysql -ss $mysql_options -e 'SELECT 1' &> /dev/null; then
                        mysql -ss $mysql_options -e "$statement"
                        break
                    fi
                    sleep 1
                done
            fi
        else
             if ! cat /dev/stdin | mysql -ss $mysql_options &> /dev/null; then
                for i in `seq 30 -1 0`; do
                    if mysql -ss $mysql_options -e 'SELECT 1' &> /dev/null; then
                        cat /dev/stdin | mysql -ss $mysql_options &> /dev/null
                        break
                    fi
                    sleep 1
                done
            fi
        fi
    }
fi

echo 'MySQL init process in progress...'

for f in /docker-entrypoint-initdb.d/*; do
    for i in `seq 30 -1 0`; do
        if execute 'SELECT 1' &> /dev/null; then
            case "$f" in
                *.sh)     echo "restoring: $(basename "$f")"; . "$f" ;;
                *.sql)    echo "restoring: $(basename "$f")"; execute < "$f" ;;
                *.sql.gz) echo "restoring: $(basename "$f")"; gunzip -c "$f" | execute ;;
                *)        echo "ignoring: $(basename "$f")" ;;
            esac
            break
        fi
        sleep 1
    done
done
