#!/usr/bin/env bash
# hooks/pre_build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Pre_build hook starting..."
if [ "$COMMIT_MSG" != "" ]; then
	GIT_LOG="$(git show -s $SOURCE_COMMIT | grep -i -E 'mysql57|mysql5\.7|mysql 5\.7|mysql all|db all|update all images')"

	if [ -z "$GIT_LOG" ]; then
		echo "[***] Aborted: Nothing to do for MySQL 5.7!"
		exit 1
	fi
fi

echo "[***] Found keyword for MySQL 5.7: Continue with build..."
