#!/usr/bin/env sh

# Set user defined timezone
ln -sf /usr/share/zoneinfo/${TZ:-UTC} /etc/localtime

# Create host userid/groupid for the apache and fpm processes user
create_user ${APP_USER_ID:-1000} ${APP_GROUP_ID:-1000}

# PHP configuration
if [ -d "${PHP_INI_DIR}" ]; then

    PHP_MAJMIN_VERSION=$(php-config --version | awk -F. '{print $1*100+$2}')
    XDEBUG_REMOTE_HOST_IP=${XDEBUG_REMOTE_HOST:-$(ip route | awk '/default/ { print $3 }')}

    # Activate development/production php.ini
    cp ${PHP_INI_DIR}/php.ini-${PHP_ENV:-production} ${PHP_INI_DIR}/php.ini

    echo "date.timezone=${TZ:-UTC}" >${PHP_INI_DIR}/conf.d/user-date-time.ini

    if test $PHP_MAJMIN_VERSION -lt 800; then
        echo "xdebug.remote_host=${XDEBUG_REMOTE_HOST_IP}" >${PHP_INI_DIR}/conf.d/user-xdebug-remote-host.ini
    else
        echo "xdebug.client_host=${XDEBUG_REMOTE_HOST_IP}" >${PHP_INI_DIR}/conf.d/user-xdebug-remote-host.ini
    fi

fi

update-ca-certificates

exec "$@"
