#!/usr/bin/env bash
# hooks/post_push
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Post_push hook starting..."

## Build on Dockerhub
ROOT_DIR="/src/$BUILD_CODE"
ENV_FILE="$ROOT_DIR/.env"

if [ ! -e "$ENV_FILE" ]; then
	echo "$ENV_FILE not found!"
	exit 1
fi

echo "[---] Load: $ENV_FILE"
source $ENV_FILE

if [ -z "$MARIADB105_VERSION" ]; then
	echo "$MARIADB104_VERSION is empty!"
	exit 1
fi

## Tag the image with version.
echo "[---] Adding tag $MARIADB104_VERSION to latest"
docker tag $IMAGE_NAME $DOCKER_REPO:$MARIADB104_VERSION

## Push the image with version.
echo "[---] Push the image with version $MARIADB104_VERSION."
docker push $DOCKER_REPO:$MARIADB104_VERSION

echo "[***] ...post_push hook complete."
