#!/usr/bin/env bash
# hooks/pre_build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Pre_build hook starting..."
if [ "$COMMIT_MSG" != "" ]; then
	GIT_LOG="$(git show -s $SOURCE_COMMIT | grep -i -E 'php73|php7\.3|php 7\.3|php all|update all images')"

	if [ -z "$GIT_LOG" ]; then
		echo "[***] Aborted: Nothing to do for PHP7.3!"
		exit 1
	fi
fi

echo "[***] Found keyword for PHP7.3: Continue with build..."
