#!/usr/bin/env bash
# hooks/pre_build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Pre_build hook starting..."
if [ "$COMMIT_MSG" != "" ]; then
	GIT_LOG="$(git show -s $SOURCE_COMMIT | grep -i -E 'apache24|apache2\.4|apache 2\.4|apache all|httpd all|update all images')"

	if [ -z "$GIT_LOG" ]; then
		echo "[***] Aborted: Nothing to do for Apache 2.4!"
		exit 1
	fi
fi

echo "[***] Found keyword for Apache 2.4: Continue with build..."
